{
  "build": {
    "publish": "dist",
    "command": "pnpm build"
  },
  "redirects": [
    {
      "from": "/*",
      "to": "/index.html",
      "status": 200
    }
  ],
  "headers": [
    {
      "for": "/assets/*",
      "values": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    },
    {
      "for": "*.js",
      "values": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    },
    {
      "for": "*.css",
      "values": {
        "Cache-Control": "public, max-age=31536000, immutable"
      }
    }
  ]
}